version: "3.9"
services:

  # setup db
  db-setup:
    build:
      context: ./src/pet_match_stack/db-setup
      dockerfile: db-setup.Dockerfile
    # create shell
    tty: true
    env_file: ./.env
    ports: 
      - "8002:8002"
    networks: 
    - pet_match_network
    # mount data to db setup container
    volumes:
      - type: volume
        # use the named volume as the source
        source: pet-data
        # i.e. your local_dir_absolute path will be mounted to target of next section (bind)
        target: $BASE_PATH/data/raw
        volume:
          nocopy: true
      - type: bind
        # use the named volume's target as the source
        source: $BASE_PATH/data/raw
        target: /app/data
        # do not allow app interface to write to pet-data volume
        read_only: true

  # fastapi backend
  fastapi:
    build:
      context: ./src/pet_match_stack/api
      dockerfile: fastapi.Dockerfile
    # create shell
    tty: true
    # mount local user data file to fastapi container
    volumes:
      - "$BASE_PATH/src/pet_match_stack/api/app:/src/app"
    ports: 
      - "8086:8086"
    networks:
    - pet_match_network

  # petmatch model backend
  model-backend:
    build:
      context: ./src/pet_match_stack/api/model-api
      dockerfile: petmatch-model-backend.Dockerfile
    # create shell
    tty: true
    # mount local user data file to fastapi models container
    volumes:
      - "$BASE_PATH/src/pet_match_stack/api/model-api:/src/app"
    ports: 
      - "8087:8087"
    networks:
    - pet_match_network


volumes:
  pet-data:
  user-rankings:
  code:


# make sure to add containers to this network
networks:
  pet_match_network:
